version: "3.1"
services:
  frontend:
    build: ./usr/src/app
    image: tilt/react/demo-react-app-image
    container_name: demo-react-app
    ports: 
      - 3000:3000
    # volumes:
    #  - .:/app
    #  - ./node_modules:/app/node_modules
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    command: yarn start