# Use root/example as user/password credentials
version: '3.1'

services:
  database:
    image: mysql:latest
    restart: always
    container_name: demo_mysql
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=password # TODO: Manage secrets
     - MYSQL_DATABASE=demoDatabase
